name: GitHub actions Maven Build example

on:
  push: 
    branches: [ master ]

jobs:
  build: 
    runs-on: ubuntu-latest

    steps:
      - name: Step1 - Checkout main branch from GitHub
        uses: actions/checkout@v2

      - name: Step2 - Setup JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Step3 - Have GitHub actions build Maven project
        run: mvn -B package --file pom.xml

      - name: Step4 - List the current directory
        run: ls -a

      - name: Step5 - What is in te current directory
        run: |
          cd target
          ls -a
